sudo: required
services:
  - docker

before_install:
  - docker build -t chrismuising/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true chrismuising/docker-react npm run test

deploy:
  provider: azure_web_apps
  site: udemy-web.azurewebsites.net
  on:
    branch: master
